from __future__ import annotations

from sq_bi_contracts.enums import ExportFormat
from sq_bi_contracts.exports import ReportSnapshot
from sq_bi_contracts.query import QueryResult


def render_artifact(
    export_format: ExportFormat,
    title: str,
    query_results: list[QueryResult],
    report_snapshot: ReportSnapshot | None,
    summary: str | None,
) -> tuple[bytes, str]:
    lines = _snapshot_lines(title, query_results, report_snapshot, summary)
    if export_format == ExportFormat.PDF:
        return _render_pdf(lines), "application/pdf"
    raise ValueError(f"Unsupported export format: {export_format}")


def _snapshot_lines(
    title: str,
    query_results: list[QueryResult],
    report_snapshot: ReportSnapshot | None,
    summary: str | None,
) -> list[str]:
    lines = [title]
    if report_snapshot is not None:
        lines.append(f"Report skill: {report_snapshot.report_skill_id}")
        lines.append(f"Generated by: {report_snapshot.generated_by}")
        lines.append(f"Generated at: {report_snapshot.generated_at.isoformat()}")
    if summary:
        lines.append(f"Summary: {summary}")

    for result in query_results:
        lines.append(f"Query: {result.query_id}")
        lines.append(f"Audit: {result.audit_id}")
        lines.append(f"Lineage: {result.lineage.lineage_id}")
        lines.append(f"Columns: {', '.join(result.columns)}")
        lines.append(f"Rows: {len(result.rows)}")
        for row in result.rows[:20]:
            values = ["" if value is None else str(value) for value in row]
            lines.append(" | ".join(values))
    return lines


def _render_pdf(lines: list[str]) -> bytes:
    text = "\\n".join(line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)") for line in lines[:40])
    stream = f"BT /F1 12 Tf 72 740 Td 14 TL ({text}) Tj ET"
    objects = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        "/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        f"<< /Length {len(stream.encode('utf-8'))} >>\nstream\n{stream}\nendstream",
    ]
    chunks = [b"%PDF-1.4\n"]
    offsets: list[int] = []
    for index, obj in enumerate(objects, start=1):
        offsets.append(sum(len(chunk) for chunk in chunks))
        chunks.append(f"{index} 0 obj\n{obj}\nendobj\n".encode("utf-8"))
    xref_offset = sum(len(chunk) for chunk in chunks)
    xref = ["xref", f"0 {len(objects) + 1}", "0000000000 65535 f "]
    xref.extend(f"{offset:010d} 00000 n " for offset in offsets)
    chunks.append(("\n".join(xref) + "\n").encode("utf-8"))
    chunks.append(f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\n".encode("utf-8"))
    chunks.append(f"startxref\n{xref_offset}\n%%EOF\n".encode("utf-8"))
    return b"".join(chunks)
